language: csharp
solution: NetworkTablesCore.sln

os:
  - linux
  - osx

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      libstdc++6-4.7-dbg

install:
  - nuget restore NetworkTablesCore.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=AppVeyor NetworkTablesCore.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./NetworkTablesCore.Test/Output/NetworkTablesCore.Test.dll
