language: csharp
solution: NetworkTablesCore.sln

addons:
  apt:
    sources:
      ubuntu-toolchain-r-test
    packages:
      libstdc++6-4.7-dbg

install:
  - nuget restore NetworkTablesCore.sln
  - nuget install NUnit.Console -Pre -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release NetworkTablesCore.sln
  - mono ./testrunner/NUnit.Console.3.0.0-rc-2/tools/nunit3-console.exe ./NetworkTablesCore.Test/Output/NetworkTablesCore.Test.dll --where "cat == Client"
  - mono ./testrunner/NUnit.Console.3.0.0-rc-2/tools/nunit3-console.exe ./NetworkTablesCore.Test/Output/NetworkTablesCore.Test.dll --where "cat == Server"

